import 'package:flutter/material.dart';

import './models/day_model.dart';
import './models/exercise_model.dart';

var DUMMY_DAYS = [
  Day(
    id: 'd1',
    title: 'Первый день',
  ),
  Day(
    id: 'd2',
    title: 'Второй день',
  ),
  Day(
    id: 'd3',
    title: 'Третий день',
  ),
  Day(
    id: 'd4',
    title: 'Четвёртый день',
  ),
  Day(
    id: 'd5',
    title: 'Пятый день',
  ),
  Day(
    id: 'd6',
    title: 'Шестой день',
  ),
  Day(
    id: 'd7',
    title: 'Седьмой день',
  ),
  Day(
    id: 'd8',
    title: 'Восьмой день',
  ),
  Day(
    id: 'd9',
    title: 'Девятый день',
  ),
  Day(
    id: 'd10',
    title: 'Десятый день',
  ),
  Day(
    id: 'd11',
    title: 'Одиннадцатый день',
  ),
  Day(
    id: 'd12',
    title: 'Двенадцатый день',
  ),
];

var DUMMY_EXERCISES = [
  Exercise(
    id: 'e1',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Жим штанги лёжа',
    weight: 40,
    set: 4,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e2',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Тяга с нижнего блока',
    weight: 20,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e3',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Сведение рук в тренажёре бабочка',
    weight: 40,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e4',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Сплит присед с гантелями',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e5',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Махи гантелями в стороны стоя',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e6',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Махи гантелей сидя в наклоне',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e7',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Подъём штанги на бицепс стоя',
    weight: 20,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e8',
    days: ['d1', 'd4', 'd7', 'd10'],
    title: 'Разгибание рук с гантелью сидя',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e9',
    days: ['d2', 'd5', 'd8', 'd11'],
    title: 'Подтягивания на перекладине',
    weight: 0,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e10',
    days: ['d2', 'd5', 'd8', 'd11'],
    title: 'Жим гантелей лёжа на горизонтальной скамье',
    weight: 20,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e11',
    days: ['d2', 'd5', 'd8', 'd11'],
    title: 'Тяга штанги к животу в наклоне',
    weight: 30,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e12',
    days: ['d2', 'd5', 'd8', 'd11'],
    title: 'Зашагивания на платформу с гантелями',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e13',
    days: ['d2', 'd5', 'd8', 'd11'],
    title: 'Махи с нижнего блока в кроссовере на дельты',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e14',
    days: ['d2', 'd5', 'd8', 'd11'],
    title: 'Подъём гантелей на бицепс стоя',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e15',
    days: ['d2', 'd5', 'd8', 'd11'],
    title: 'Разгибание рук на блоке стоя',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e16',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Приседания со штангой на плечах',
    weight: 40,
    set: 4,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e17',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Подъём на носки',
    weight: 40,
    set: 4,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e18',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Тяга нижнего блока узким хватом',
    weight: 40,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e19',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Жим гантелей на наклонной скамье',
    weight: 20,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e20',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Румынская тяга',
    weight: 40,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e21',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Махи гантелями в стороны сидя',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e22',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Махи гантелей сидя',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e23',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Подъём штанги на скамье Скотта',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e24',
    days: ['d3', 'd6', 'd9', 'd12'],
    title: 'Французский жим лёжа',
    weight: 10,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
  Exercise(
    id: 'e25',
    days: [
      'd1',
      'd2',
      'd3',
      'd4',
      'd5',
      'd6',
      'd7',
      'd8',
      'd9',
      'd10',
      'd11',
      'd12'
    ],
    title: 'Скручивания на пресс',
    weight: 0,
    set: 3,
    repeat: 12,
    // imageUrl: '',
  ),
];
